{{- if .Values.ingress.tls }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "events-service.fullname" . }}
  labels:
{{ include "events-service.labels" . | indent 4 }}
spec:
  secretName: {{ .Values.cert.secretName }}
  dnsNames:
  {{- range .Values.ingress.hosts }}
  - {{ .host | quote }}
  {{- end }}
  acme:
    config:
    - http01:
        ingressClass: {{ .Values.cert.ingressClass }}
      domains:
      {{- range .Values.ingress.hosts }}
      - {{ .host | quote }}
      {{- end }}
  issuerRef:
    name: {{ .Values.cert.issuer }}
    kind: ClusterIssuer
{{- end }}