replicaCount: 2

deployment:
  maxUnavailable: 1
  maxSurge: 1

image:
  repository: artemkv/journey-events-service
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

container:
  port: 8000

service:
  type: ClusterIP
  port: 80

serviceAccount:
  enabled: true
  name: events-service-account
  projectName: journey-250514

ingress:
  enabled: true
  annotations:
    # ingress.kubernetes.io/ssl-redirect: "true"
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: svc.artemkv.net
      paths:
        - /events

  tls:
    - secretName: events-service-tls
      hosts:
        - svc.artemkv.net

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 16Mi

env:
  nodePort: "8000"
  nodeIP: "0.0.0.0"
  actionTopic: "projects/journey-250514/topics/action-topic"
  errorTopic: "projects/journey-250514/topics/error-topic"

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - journey-events-service
      topologyKey: "kubernetes.io/hostname"